export const readonlyLuckyNumber = true; // Variável única para todos os Politikoz

export const politikozList = [
  {
    id: 1,
    type: "President",
    name: "#02526",
    cargo: "Presidente",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 87,
    dirtyMoney: 64,
    influence: 45,
    cleanMoney: 22,
    bribePower: 75,
    scapegoats: 6,
    luckyNumber: 47,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 156,
    type: "President",
    name: "#02526",
    cargo: "Presidente",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 87,
    dirtyMoney: 64,
    influence: 45,
    cleanMoney: 22,
    bribePower: 75,
    scapegoats: 6,
    luckyNumber: 47,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 323,
    type: "President",
    name: "#02526",
    cargo: "Presidente",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 87,
    dirtyMoney: 64,
    influence: 45,
    cleanMoney: 22,
    bribePower: 75,
    scapegoats: 6,
    luckyNumber: 47,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 699,
    type: "President",
    name: "#02526",
    cargo: "Presidente",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 87,
    dirtyMoney: 64,
    influence: 45,
    cleanMoney: 22,
    bribePower: 75,
    scapegoats: 6,
    luckyNumber: 47,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 856,
    type: "President",
    name: "#02526",
    cargo: "Presidente",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 87,
    dirtyMoney: 64,
    influence: 45,
    cleanMoney: 22,
    bribePower: 75,
    scapegoats: 6,
    luckyNumber: 47,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 2,
    type: "Senator",
    name: "#05897",
    cargo: "Senador",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 39,
    dirtyMoney: 19,
    influence: 88,
    cleanMoney: 12,
    bribePower: 33,
    scapegoats: 3,
    luckyNumber: 59,
    isImprisoned: true,
    prisonEpochs: 2,
    releaseCost: 20,
  },
  {
    id: 3,
    type: "Minister",
    name: "#03265",
    cargo: "Ministro",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 66,
    dirtyMoney: 73,
    influence: 31,
    cleanMoney: 55,
    bribePower: 90,
    scapegoats: 4,
    luckyNumber: 91,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 4,
    type: "Governor",
    name: "#01455",
    cargo: "Governador",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 25,
    dirtyMoney: 49,
    influence: 60,
    cleanMoney: 42,
    bribePower: 18,
    scapegoats: 7,
    luckyNumber: 3,
    isImprisoned: true,
    prisonEpochs: 1,
    releaseCost: 10,
  },
  {
    id: 5,
    type: "Federal Deputy",
    name: "#02587",
    cargo: "Deputado Federal",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 44,
    dirtyMoney: 95,
    influence: 83,
    cleanMoney: 17,
    bribePower: 56,
    scapegoats: 2,
    luckyNumber: 66,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 6,
    type: "State Deputy",
    name: "#01479",
    cargo: "Deputado Estadual",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 73,
    dirtyMoney: 36,
    influence: 92,
    cleanMoney: 48,
    bribePower: 10,
    scapegoats: 1,
    luckyNumber: 82,
    isImprisoned: true,
    prisonEpochs: 3,
    releaseCost: 30,
  },
  {
    id: 7,
    type: "Mayor",
    name: "#02498",
    cargo: "Prefeito",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 56,
    dirtyMoney: 78,
    influence: 13,
    cleanMoney: 26,
    bribePower: 34,
    scapegoats: 0,
    luckyNumber: 11,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 8,
    type: "Councilor",
    name: "#00256",
    cargo: "Vereador",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 21,
    dirtyMoney: 14,
    influence: 80,
    cleanMoney: 67,
    bribePower: 45,
    scapegoats: 5,
    luckyNumber: 24,
    isImprisoned: true,
    prisonEpochs: 2,
    releaseCost: 20,
  },
  {
    id: 9,
    type: "President",
    name: "#00487",
    cargo: "Presidente",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 91,
    dirtyMoney: 55,
    influence: 63,
    cleanMoney: 84,
    bribePower: 77,
    scapegoats: 2,
    luckyNumber: 5,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 10,
    type: "Senator",
    name: "#00023",
    cargo: "Senador",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 13,
    dirtyMoney: 82,
    influence: 70,
    cleanMoney: 91,
    bribePower: 14,
    scapegoats: 6,
    luckyNumber: 38,
    isImprisoned: true,
    prisonEpochs: 1,
    releaseCost: 10,
  },
  {
    id: 11,
    type: "Minister",
    name: "#00045",
    cargo: "Ministro",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 42,
    dirtyMoney: 33,
    influence: 55,
    cleanMoney: 49,
    bribePower: 20,
    scapegoats: 0,
    luckyNumber: 69,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 12,
    type: "Governor",
    name: "#00004",
    cargo: "Governador",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 38,
    dirtyMoney: 77,
    influence: 91,
    cleanMoney: 35,
    bribePower: 63,
    scapegoats: 3,
    luckyNumber: 12,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 13,
    type: "Federal Deputy",
    name: "#00008",
    cargo: "Deputado Federal",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 47,
    dirtyMoney: 25,
    influence: 66,
    cleanMoney: 58,
    bribePower: 37,
    scapegoats: 8,
    luckyNumber: 90,
    isImprisoned: true,
    prisonEpochs: 2,
    releaseCost: 20,
  },
  {
    id: 14,
    type: "State Deputy",
    name: "#00009",
    cargo: "Deputado Estadual",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 58,
    dirtyMoney: 30,
    influence: 43,
    cleanMoney: 76,
    bribePower: 29,
    scapegoats: 1,
    luckyNumber: 13,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 15,
    type: "Mayor",
    name: "#00235",
    cargo: "Prefeito",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 63,
    dirtyMoney: 46,
    influence: 17,
    cleanMoney: 61,
    bribePower: 72,
    scapegoats: 0,
    luckyNumber: 56,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 16,
    type: "Councilor",
    name: "#00054",
    cargo: "Vereador",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 40,
    dirtyMoney: 85,
    influence: 97,
    cleanMoney: 10,
    bribePower: 81,
    scapegoats: 7,
    luckyNumber: 27,
    isImprisoned: true,
    prisonEpochs: 3,
    releaseCost: 30,
  },
  {
    id: 17,
    type: "President",
    name: "#00269",
    cargo: "Presidente",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 79,
    dirtyMoney: 62,
    influence: 22,
    cleanMoney: 44,
    bribePower: 53,
    scapegoats: 5,
    luckyNumber: 74,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 18,
    type: "Senator",
    name: "#00458",
    cargo: "Senador",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 15,
    dirtyMoney: 69,
    influence: 29,
    cleanMoney: 33,
    bribePower: 19,
    scapegoats: 4,
    luckyNumber: 60,
    isImprisoned: true,
    prisonEpochs: 2,
    releaseCost: 20,
  },
  {
    id: 19,
    type: "Minister",
    name: "#01568",
    cargo: "Ministro",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 88,
    dirtyMoney: 41,
    influence: 36,
    cleanMoney: 93,
    bribePower: 48,
    scapegoats: 6,
    luckyNumber: 20,
    isImprisoned: false,
    prisonEpochs: 0,
    releaseCost: 0,
  },
  {
    id: 20,
    type: "Governor",
    name: "#00056",
    cargo: "Governador",
    historico: ["Was elected in July 2025 and won 58 ₳."],
    stamina: 60,
    dirtyMoney: 93,
    influence: 71,
    cleanMoney: 14,
    bribePower: 65,
    scapegoats: 1,
    luckyNumber: 41,
    isImprisoned: true,
    prisonEpochs: 1,
    releaseCost: 10,
  },
];
